channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cxx-compiler
  - cuda-toolkit
  - cuda-compiler
  - pytorch-cuda=11.8
  - pytorch
  - torchvision
  - cudatoolkit=11.8
  - pip
  - pip:
    - scikit-learn
    - h5py
    - tqdm
    - pandas
    - mamba-ssm
    - ftfy
    - regex
    - fsspec
    - timm>=1.0.7
    - huggingface_hub
    - transformers[sentencepiece]
    - braceexpand
    - kaggle
    - accelerate
    - open_clip_torch

